# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

permissions:
  id-token: write
  contents: read
  checks: write

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:ci

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: JEST Tests ${{ matrix.node-version }}
        path: junit*.xml
        reporter: jest-junit

    - name: Check if pacts are uptodate.
      run: |
        if [[ $(git status pacts/ --porcelain) ]]; then
          echo "pacts in the repository are not uptodate."
          exit 1
        fi

    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1

    - name: Start stack with Docker Compose
      run: docker-compose -f smoketest/docker-compose.yml up -d
      env:
        COMPOSE_PROJECT_NAME: smoke

    - name: Run Playwright smoke test
      run: npx playwright test smoketest/smoketest.spec.ts

    - name: Shut down stack
      if: always()
      run: docker-compose -f smoketest/docker-compose.yml down

